# Weaviate Schema Configuration
classes:
  - class: UserStory
    description: User story from Azure DevOps
    vectorizer: none  # We provide embeddings directly
    properties:
      - name: story_id
        dataType: 
          - string
        description: The ID of the user story in Azure DevOps
      - name: project_id
        dataType:
          - string
        description: The ID of the project in Azure DevOps
      - name: title
        dataType:
          - text
        description: The title of the user story
      - name: description
        dataType:
          - text
        description: The description of the user story
      - name: created_at
        dataType:
          - date
        description: The creation date of the user story

  - class: TestCase
    description: Test case generated for a user story
    vectorizer: none  # We provide embeddings directly
    properties:
      - name: story_id
        dataType: 
          - string
        description: The ID of the user story this test case belongs to
      - name: test_case_id
        dataType:
          - string
        description: The ID of the test case in Azure DevOps
      - name: title
        dataType:
          - text
        description: The title of the test case
      - name: description
        dataType:
          - text
        description: The description of the test case
      - name: test_case_text
        dataType:
          - text
        description: Markdown representation of the test case
      - name: test_case_csv
        dataType:
          - text
        description: CSV representation of the test case
      - name: steps
        dataType:
          - text[]
        description: JSON string array of steps with action and expected result
      - name: generated_at
        dataType:
          - date
        description: The generation date of the test case
